"""add Medicacao model

Revision ID: 1a95f375c825
Revises: a47e5f12cdb3
Create Date: 2025-04-18 00:53:00.376160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a95f375c825'
down_revision = 'a47e5f12cdb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gato_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('dosagem', sa.String(length=100), nullable=False),
    sa.Column('frequencia', sa.String(length=100), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gato_id'], ['gato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicacao')
    # ### end Alembic commands ###
